steps:
- id: 'image-build'
  name: 'gcr.io/kaniko-project/executor:v1.9.0'
  waitFor: ['-']
  args: [
    '--snapshotMode=redo',
    '--use-new-run',
    '--dockerfile=infrastructure/containers/Dockerfile.backend.cloud',
    '--destination=gcr.io/$PROJECT_ID/nimble-challenge-backend:$COMMIT_SHA',
    '--destination=gcr.io/$PROJECT_ID/nimble-challenge-backend:latest',
    '--cache=true',
    '--cache-ttl=72h',
    '--compressed-caching=false'
  ]

- id: deploy-cloud-run
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  waitFor: ['image-build']
  entrypoint: sh
  args: ['-c', "\
    gcloud beta run deploy nimble-challenge-backend \
    --image gcr.io/$PROJECT_ID/nimble-challenge-backend:$COMMIT_SHA \
    --region us-central1 \
    --platform managed \
    --cpu 1 --memory=256Mi --max-instances 1 \
    --add-cloudsql-instances $_CLOUD_SQL_INSTANCE_CONNECTION_NAME \
    --allow-unauthenticated \
    --set-secrets $(cat infrastructure/.secrets_${_ENVIRONMENT} | paste -s -d ',' -) \
    --set-env-vars \"ENVIRONMENT=$_ENVIRONMENT\" \
    --set-env-vars \"GCLOUD_PROJECT=$PROJECT_ID\" \
    --set-env-vars \"ALLOWED_CORS_ORIGINS_REGEX=$_ALLOWED_CORS_ORIGINS_REGEX\" \
    --set-env-vars \"GCP_PROJ_ID=$_GCP_PROJ_ID\" \
    --set-env-vars \"GOOGLE_APPLICATION_CREDENTIALS=$_GOOGLE_APPLICATION_CREDENTIALS\" \
    --set-env-vars \"BACKEND_DB_HOST=/cloudsql/$_CLOUD_SQL_INSTANCE_CONNECTION_NAME\" \
    --set-env-vars \"DB_NAME=backend\" \
    --set-env-vars \"DB_PORT=5432\" \
    \ "
  ]
logsBucket: '$_LOGS_BUCKET'
timeout: 900s
options:
  logging: GCS_ONLY
